### ISSUE TITLE
\skbem is broken (TexLive 2015)

### ISSUE THREAD

**Issue by rbenit68** [vdmeer/skb-latex#4]
Building included user-guide.tex I get:

```
   (./user-guide/repository/getting-started/config-opt-table.tex
```

! Missing { inserted.
<inserted text> 
                {
l.1       \skbem[code]{root}    &
                                  Sets the root path of the SKB. Everything ...

I think it could be related to changes in keyval package(s), but the solution is beyond my tex knowledge.

SOLVED:

It is not \skbem, it is \skbcode actually:

Instead 

```
\newcommand{\skbcode}[1]{%
  \lstinline[basicstyle=\ttfamily]{#1}%
}%
```

You have to define

```
\newcommand{\skbcode}[1]{%
  \lstinline[basicstyle=\ttfamily]!#1!%
}%
```

See [listings package documentation](http://mirrors.ctan.org/macros/latex/contrib/listings/listings.pdf)

**Comment by vdmeer** [comment]
Yes, the problem is skbcode using lstlistings as inline with {} instead of || for the argument. I fixed that now, will publish v0.53 soon (with some other changes).

Thanks for comment and solution!
/sven

**Comment by vdmeer** [comment]
You'll now find a tag v0.53-rc1 on the master branch fixing the \skbem[code] problem. I do want to do some other changes before releasing it to CTAN, that might take a while. But you can build and install the sty with the fix locally.

Thanks!

**Comment by vdmeer** [comment]
One more comment: apologies for the late reply, I did not put a watch on this project back in 2011. I did run into the same problem you encountered a couple of weeks back, and then went back to this project, and only then saw you opening the issue.

I have a watch on the project now.

Thanks for using the package :) hope it helps you!
/sven
